openapi: 3.0.0
info:
  title: 'Reference Books API Microservice'
  description: 'Reference Books API Microservice, Version v1'
  contact:
    name: 'Support Team'
    email: support@ultainfinity.com
  version: v1
servers:
  -
    url: 'https://localhost:18112/v1'
    description: 'Reference Books API Microservice, Version v1'
paths:
  /admin/currencies:
    get:
      tags:
        - 'Admin / Currencies'
      summary: 'Show list of currencies'
      description: 'Show list of currencies'
      operationId: 9a11a59f174c4f94a774b6613e8fc56e
      parameters:
        -
          name: limit
          in: query
          description: 'count of currencies in return'
          required: false
          schema:
            type: integer
            default: 20
        -
          name: page
          in: query
          description: 'page of list'
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Success
      security:
        -
          default:
            - ManagerRead
            - User
            - ManagerWrite
      x-auth-type: 'Application & Application User'
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: 'false'
    post:
      tags:
        - 'Admin / Currencies'
      summary: 'Create currency'
      description: 'Create currency'
      operationId: 991a9fce0b2d1065aaee23d8c492ab31
      parameters:
        -
          name: title
          in: path
          description: 'Currency title'
          required: true
          schema:
            type: strigng
        -
          name: status
          in: query
          description: 'Currency status. Types of statuses: Active = 1, Inactive = 0'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
      security:
        -
          default:
            - ManagerRead
            - User
            - ManagerWrite
      x-auth-type: 'Application & Application User'
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: 'false'
  '/admin/currencies/{id}/update-status':
    patch:
      tags:
        - 'Admin / Currencies'
      summary: 'Update status of currency'
      description: 'Update status of currency'
      operationId: 1661e0001800cb8ba34c15ec238ee879
      parameters:
        -
          name: id
          in: path
          description: 'Currency id'
          required: true
          schema:
            type: integer
        -
          name: status
          in: query
          description: 'Currency status. Types of statuses: Active = 1, Inactive = 0'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
      security:
        -
          default:
            - ManagerRead
            - User
            - ManagerWrite
      x-auth-type: 'Application & Application User'
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: 'false'
  /currencies:
    get:
      tags:
        - Currencies
      summary: 'Getting a list of currencies'
      description: 'Getting a list of currencies'
      operationId: 5d6629527f25084ed422fe191e818951
      parameters:
        -
          name: type
          in: query
          description: 'Currency type (fiat | crypto | token | virtual)'
          required: false
          schema:
            type: string
            default: fiat
      responses:
        '200':
          description: Success
      security:
        -
          default:
            - ManagerRead
            - User
            - ManagerWrite
      x-auth-type: 'Application & Application User'
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: 'false'
  /currencies/rate:
    get:
      tags:
        - Currencies
      summary: 'Show list of currencies'
      description: 'Show list of currencies'
      operationId: b469d9ee97ebda1d10f38685cfbb1001
      parameters:
        -
          name: from_currency
          in: query
          description: 'from '
          required: false
          schema:
            type: integer
            default: 20
        -
          name: to_currency
          in: query
          description: 'page of list'
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Success
      security:
        -
          default:
            - ManagerRead
            - User
            - ManagerWrite
      x-auth-type: 'Application & Application User'
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: 'false'
  /currencies/codes:
    get:
      tags:
        - Currencies
      summary: 'Method for get codes of currencies'
      description: 'Get codes of currencies'
      operationId: 24bed7f583e55c004df686ffdf65e21e
      responses:
        '200':
          description: Success
      security:
        -
          default:
            - ManagerRead
            - User
            - ManagerWrite
      x-auth-type: 'Application & Application User'
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: 'false'
components:
  securitySchemes:
    default:
      type: oauth2
      description: 'Auth Scheme'
      flows:
        implicit:
          authorizationUrl: 'https://sumraid.com/oauth2'
          scopes:
            ManagerRead: 'Manager can read'
            User: 'User access'
            ManagerWrite: 'Manager can write'
